basketball/basketball/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.index, name='index'),
    path("accounts/", include('allauth.urls')),
    path("calendar/",include("calendar_basket.urls")),
    path("clasificacion/",include("clasificacion.urls")),
    path("statistics/",include("statistics_basketball.urls")),
    path("perfil/",include("perfil.urls")),
    path('api/v1/api-auth/', include('rest_framework.urls', namespace='rest_framework'), name='api-auth'),
    path('api/v1/', include('calendar_basket.api.v1.urls')),
    path('api/v1/', include('clasificacion.api.v1.urls')),
    path('api/v1/', include('statistics_basketball.api.v1.urls')),
    path('api/v1/', include('perfil.api.v1.urls')),
]

basketball/perfil/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = "perfil"

urlpatterns = [
    path('complete-player-profile/', views.complete_player_profile_view, name='complete_player_profile'),
    path('', views.perfil, name='perfil'),
]

basketball/statistics_basketball/api/v1/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'statistics', views.StatisticsViewSet)
router.register(r'team-statistics', views.TeamStatisticsViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

basketball/statistics_basketball/urls.py
from django.urls import path
from . import views

app_name = "statistics"

urlpatterns = [
    path("", views.statistics, name="statistics"),
    path("<int:id_game>/", views.view_statistics, name="statistics_game"),
    path("add/<int:id_game>/", views.add_statistics, name="add_statistics"),
    path("shot_plot/<int:id_game>/", views.bokeh_shot_stats, name="shot_plot"),
    path("playerstats/", views.bokeh_player_stats, name="player_stats"),
    path("team_statistics/", views.team_statistics, name="team_statistics"),
]

basketball/statistics_basketball/models.py
from django.db import models
from calendar_basket.models import Calendar, Teams
from perfil.models import Players


class Statistics(models.Model):
    id = models.BigAutoField(primary_key=True)
    id_team = models.ForeignKey(Teams, models.DO_NOTHING, db_column='id_team', blank=True, null=True)
    id_player = models.ForeignKey(Players, models.DO_NOTHING, db_column='id_player', blank=True, null=True)
    id_game = models.ForeignKey(Calendar, models.DO_NOTHING, db_column='id_game', blank=True, null=True)
    mins = models.BigIntegerField(blank=True, null=True, default=0)
    fgm = models.BigIntegerField(blank=True, null=True, default=0)
    fga = models.BigIntegerField(blank=True, null=True, default=0)
    fgperc = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, default=0)
    threepm = models.BigIntegerField(blank=True, null=True, default=0)
    threepa = models.BigIntegerField(blank=True, null=True, default=0)
    threepperc = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, default=0)
    ftm = models.BigIntegerField(blank=True, null=True, default=0)
    fta = models.BigIntegerField(blank=True, null=True, default=0)
    ftperc = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, default=0)
    reb = models.BigIntegerField(blank=True, null=True, default=0)
    ast = models.BigIntegerField(blank=True, null=True, default=0)
    stl = models.BigIntegerField(blank=True, null=True, default=0)
    blk = models.BigIntegerField(blank=True, null=True, default=0)
    turnover = models.BigIntegerField(blank=True, null=True, default=0)
    pf = models.BigIntegerField(blank=True, null=True, default=0)
    pts = models.BigIntegerField(blank=True, null=True, default=0)
    win = models.BooleanField(blank=True, null=True, default=False)

    class Meta:
        managed = True        
        db_table = 'statistics'
        unique_together = (('id_game', 'id_player', 'id_team'),)


class ShotStatistics(models.Model):
    id = models.BigAutoField(primary_key=True)
    id_team = models.ForeignKey(Teams, models.DO_NOTHING, db_column='id_team', blank=True, null=True)
    id_player = models.ForeignKey(Players, models.DO_NOTHING, db_column='id_player', blank=True, null=True)
    id_game = models.ForeignKey(Calendar, models.DO_NOTHING, db_column='id_game', blank=True, null=True)
    id_statistics = models.ForeignKey(Statistics, models.DO_NOTHING, db_column='id_statistics', blank=True, null=True)
    x = models.BigIntegerField(blank=True, null=True)
    y = models.BigIntegerField(blank=True, null=True)
    made = models.BooleanField(blank=True, null=True, default=False)
    threep = models.BooleanField(blank=True, null=True, default=False)

    class Meta:
        managed = True        
        db_table = 'shot_statistics'
        

class TeamStatistics(models.Model):
    id_team = models.BigIntegerField(primary_key=True)
    team = models.TextField(blank=True, null=True)
    posicion = models.BigIntegerField(blank=True, null=True)
    jugados = models.BigIntegerField(blank=True, null=True)
    ganados = models.BigIntegerField(blank=True, null=True)
    perdidos = models.BigIntegerField(blank=True, null=True)
    puntos_favor = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    puntos_contra = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    dif_puntos = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    g_puntos_favor = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    g_puntos_contra = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    g_dif_puntos = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    p_puntos_favor = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    p_puntos_contra = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    p_dif_puntos = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    c_posicion = models.BigIntegerField(blank=True, null=True)
    c_jugados = models.BigIntegerField(blank=True, null=True)
    c_ganados = models.BigIntegerField(blank=True, null=True)
    c_perdidos = models.BigIntegerField(blank=True, null=True)
    c_puntos_favor = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    c_puntos_contra = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    c_dif_puntos = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    c_g_puntos_favor = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    c_g_puntos_contra = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    c_g_dif_puntos = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    c_p_puntos_favor = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    c_p_puntos_contra = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    c_p_dif_puntos = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    f_posicion = models.BigIntegerField(blank=True, null=True)
    f_jugados = models.BigIntegerField(blank=True, null=True)
    f_ganados = models.BigIntegerField(blank=True, null=True)
    f_perdidos = models.BigIntegerField(blank=True, null=True)
    f_puntos_favor = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    f_puntos_contra = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    f_dif_puntos = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    f_g_puntos_favor = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    f_g_puntos_contra = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    f_g_dif_puntos = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    f_p_puntos_favor = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    f_p_puntos_contra = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    f_p_dif_puntos = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'team_statistics'

basketball/statistics_basketball/forms.py
from django import forms
from .models import Statistics, ShotStatistics

class StatisticsForm(forms.ModelForm):
    class Meta:
        model = Statistics
        exclude = ['id_team', 'id_player', 'id_game', 'id', 'fgm', 'fga', 'fgperc', 'threepm', 'threepa', 'threepperc', 'ftperc', 'pts', 'win']

    mins = forms.IntegerField(label='Minutos', required=False, initial=0)
    ftm = forms.IntegerField(label='Tiros libres anotados', required=False, initial=0)
    fta = forms.IntegerField(label='Tiros libres intenados', required=False, initial=0)
    reb = forms.IntegerField(label='Rebotes', required=False, initial=0)
    ast = forms.IntegerField(label='Asistencias', required=False, initial=0)
    stl = forms.IntegerField(label='Robos', required=False, initial=0)
    blk = forms.IntegerField(label='Tapones', required=False, initial=0)
    turnover = forms.IntegerField(label='Pérdidas', required=False, initial=0)
    pf = forms.IntegerField(label='Faltas personales', required=False, initial=0)
    

class ShotForm(forms.Form):
    WIN_CHOICES = [
        ('', 'Todos'),
        (True, 'Win'),
        (False, 'Lose'),
    ]

    MADE_CHOICES = [
        ('', 'Todos'),
        (True, 'Anotado'),
        (False, 'Fallado'),
    ]

    win = forms.ChoiceField(choices=WIN_CHOICES, required=False, label='Win/Lose', widget=forms.Select(attrs={'class': 'mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-green-500 focus:border-green-500 sm:text-sm'}))
    made = forms.ChoiceField(choices=MADE_CHOICES, required=False, label='Anotado/Fallado', widget=forms.Select(attrs={'class': 'mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-green-500 focus:border-green-500 sm:text-sm'}))

basketball/statistics_basketball/api/v1/views.py
from rest_framework import viewsets, permissions
from statistics_basketball.models import Statistics, TeamStatistics
from .serializers import StatisticsSerializer, TeamStatisticsSerializer
from django_filters import rest_framework as filters


class StatisticsFilter(filters.FilterSet):
    id_partido = filters.NumberFilter(field_name='id_game')
    id_equipo = filters.NumberFilter(field_name='id_team')
    id_jugador = filters.NumberFilter(field_name='id_player')

    class Meta:
        model = Statistics
        fields = ['id_partido', 'id_equipo', 'id_jugador']

class TeamStatisticsFilter(filters.FilterSet):
    id_equipo = filters.NumberFilter(field_name='id_team')

    class Meta:
        model = TeamStatistics
        fields = ['id_equipo']

class StatisticsViewSet(viewsets.ModelViewSet):
    queryset = Statistics.objects.all()
    serializer_class = StatisticsSerializer
    permission_classes = [permissions.AllowAny]
    filter_backends = [filters.DjangoFilterBackend]
    filterset_class = StatisticsFilter

class TeamStatisticsViewSet(viewsets.ModelViewSet):
    queryset = TeamStatistics.objects.all()
    serializer_class = TeamStatisticsSerializer
    permission_classes = [permissions.AllowAny]
    filter_backends = [filters.DjangoFilterBackend]
    filterset_class = TeamStatisticsFilter

basketball/statistics_basketball/views.py
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from .actions import v_view_statistics, v_statistics, v_add_statistics, v_bokeh_shot_stats, v_bokeh_player_stats, v_team_statistics


@login_required
def view_statistics(request, id_game):
    context = v_view_statistics(request, id_game)
    if context is None:
        return redirect('perfil:complete_player_profile')
    return render(request, 'statistics_basketball/statistics_game.html', context)


@login_required
def statistics(request):
    context = v_statistics(request)
    if context is None:
        return redirect('perfil:complete_player_profile')

    return render(request, 'statistics_basketball/statistics.html', context)


@login_required
def add_statistics(request, id_game):
    context = v_add_statistics(request, id_game)
    if context is None:
        return redirect('perfil:complete_player_profile')
    if isinstance(context, dict):
        print("meter datos")
        return render(request, 'statistics_basketball/add_statistics.html', context)
    else:
        print("redirigir")
        return redirect('statistics:statistics_game', id_game=id_game)


@login_required
def bokeh_shot_stats(request, id_game):
    context = v_bokeh_shot_stats(request, id_game)
    if context is None:
        return redirect('perfil:complete_player_profile')

    return render(request, 'statistics_basketball/shot_plot.html', context)


@login_required
def bokeh_player_stats(request):
    context = v_bokeh_player_stats(request)
    if  not context:
        return redirect('perfil:complete_player_profile')

    return render(request, 'statistics_basketball/player_stats.html', context)


@login_required
def team_statistics(request):
    context = v_team_statistics(request)

    return render(request, 'statistics_basketball/team_statistics.html', context)

basketball/statistics_basketball/templates/statistics_basketball/add_statistics.html
{% extends "base.html" %}

{% block title %}Estadisticas{% endblock %}

{% block content %}
  <form class="max-w-sm mx-auto space-y-4 mt-8" method="post">
    {% csrf_token %}
    {% for field in form %}
      <div>
        <label for="{{ field.id }}" class="block text-sm font-medium text-gray-700">{{ field.label }}</label>
        <input name="{{ field.name }}" id="{{ field.id_for_label }}" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" type="{{ field.field.widget.input_type }}" value="{{ field.value }}" required>
      </div>
    {% endfor %}
    <button type="submit" class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-green-600 hover:bg-green-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-800">Guardar estadísticas</button>
  </form>
{% endblock %}

basketball/statistics_basketball/templates/statistics_basketball/shot_plot.html
{% extends "base.html" %}

{% block extra_head %}
   <link href="http://cdn.pydata.org/bokeh/release/bokeh-3.3.1.min.css" rel=”stylesheet” type=”text/css”>
   <link href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-3.3.1.min.css" rel=”stylesheet” type=”text/css”>
   <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
   <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js" integrity="sha256-lSjKY0/srUM9BE3dPm+c4fBo1dky2v27Gdjm2uoZaL0=" crossorigin="anonymous"></script>
   <script src="https://cdn.bokeh.org/bokeh/release/bokeh-3.3.1.min.js" crossorigin="anonymous"></script>
   <script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.3.1.min.js" crossorigin="anonymous"></script>
   <script src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.3.1.min.js" crossorigin="anonymous"></script>
   <script src="https://cdn.bokeh.org/bokeh/release/bokeh-api-3.3.1.min.js" crossorigin="anonymous"></script>
{% endblock %}

{% block title %}Shot plot{% endblock %}

{% block content %}
<div class="flex flex-col items-center mt-8">
   <h2 class="mb-2 text-lg font-semibold text-gray-900">Shot plot</h2>
   

   <p class="flex items-center text-sm text-gray-500">Como utilizar <button data-popover-target="popover-description" data-popover-placement="bottom-end" type="button"><svg class="w-4 h-4 ms-2 text-gray-400 hover:text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg><span class="sr-only">Show information</span></button></p>
   <div data-popover id="popover-description" role="tooltip" class="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72">
      <div class="p-3 space-y-2">
         <ol class="list-decimal list-inside">
            <li>
               Introducir los tiros realizados en el partido pulsando sobre la gráfica.
            </li>
            <li>
               Con cada tiro introducido en la gráfica, cambiar la columna de "Anotado" en la tabla, según si el tiro es anotado o fallado.
            </li>
            <li>
               Una vez estén introducidos todos los tiros, pulsar el botón de "Guardar tiros".
            </li>
            <li>
               Pulsar el botón de "Continuar estadísticas" para introducir las estadísticas restantes.
            </li>
         </ol>
         <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
   </svg></a>
      </div>
      <div data-popper-arrow></div>
   </div>

   {{ script| safe }}
   <a href="{% url 'statistics:add_statistics' id_game=id_game %}" class="text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 mb-20">
      Continuar estadísticas
   </a>
</div>
{% endblock %}

basketball/statistics_basketball/templates/statistics_basketball/statistics.html
{% extends "base.html" %}

{% block title %}Estadisticas{% endblock %}

{% block content %}
<div class="flex flex-col items-center mt-12">
    <h2 class="mb-2 text-lg font-semibold text-gray-900">Jornadas:</h2>
    <ol class="w-2/4 space-y-1 text-green-900 list-decimal list-inside mt-4">
    {% for partido in partidos %}
        <li>
            <span class="font-semibold text-gray-900">{{ partido.fecha_partido }}</span>: 
            <a class="font-medium text-green-700" href="{% url 'statistics:statistics_game' partido.id_game %}">{{ partido.equipo_local }} vs. {{ partido.equipo_visitante }}</a>
        </li>
    {% endfor %}
    </ol>
</div>

{% endblock %}

basketball/statistics_basketball/templates/statistics_basketball/statistics_game.html
{% extends "base.html" %}
{% load static %}

{% block title %}Estadisticas{% endblock %}

{% block content %}
<div class="bg-white border border-gray-300 rounded shadow-md p-5 text-lg mb-12 mt-5 w-auto mx-auto">
    <p class="text-center font-semibold tracking-widest text-sm">{{ partido.fecha_partido }}</p>
    <p class="text-center font-bold text-2xl text-gray-600 my-2">{{ partido.equipo_local }}</p>
    <p class="text-center font-mono text-2xl text-green-700">{{ partido.resultado_local }}</p>
    <p class="text-center font-mono text-2xl text-green-700">{{ partido.resultado_visitante }}</p>
    <p class="text-center font-bold text-2xl text-gray-600 my-2">{{ partido.equipo_visitante }}</p>
</div>

<h2 class="font-bold text-2xl text-gray-600">{{ partido.equipo_local  }}<small class="ms-2 font-semibold text-gray-500">
    {% if player.id_team.id_team == partido.id_equipo_local %}
        <a class="partido" href="{% url 'statistics:shot_plot' partido.id_game %}">Añadir estadísticas</a>
    {% endif %}
</small>
</h2>

<div class="relative overflow-x-auto shadow-md sm:rounded-lg mt-8 mb-12">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50">
            <tr>
                <th scope="col" class="px-6 py-3 text-left">Jugador</th>
                <th scope="col" class="px-4 py-3 text-center">MIN</th>
                <th scope="col" class="px-4 py-3 text-center">FGM</th>
                <th scope="col" class="px-4 py-3 text-center">FGA</th>
                <th scope="col" class="px-4 py-3 text-center">FG%</th>
                <th scope="col" class="px-4 py-3 text-center">3PM</th>
                <th scope="col" class="px-4 py-3 text-center">3PA</th>
                <th scope="col" class="px-4 py-3 text-center">3P%</th>
                <th scope="col" class="px-4 py-3 text-center">FTM</th>
                <th scope="col" class="px-4 py-3 text-center">FTA</th>
                <th scope="col" class="px-4 py-3 text-center">FT%</th>
                <th scope="col" class="px-4 py-3 text-center">REB</th>
                <th scope="col" class="px-4 py-3 text-center">AST</th>
                <th scope="col" class="px-4 py-3 text-center">STL</th>
                <th scope="col" class="px-4 py-3 text-center">BLK</th>
                <th scope="col" class="px-4 py-3 text-center">TO</th>
                <th scope="col" class="px-4 py-3 text-center">PF</th>
                <th scope="col" class="px-4 py-3 text-center">PTS</th>
            </tr>
        </thead>
        <tbody>
            {% for estadistica in estadisticas_local %}
            <tr class="bg-white border-b hover:bg-gray-50">
                <th scope="row" class="px-6 py-2 font-medium text-gray-900 whitespace-nowrap text-left">{{ estadistica.id_player.first_name }}, #{{ estadistica.id_player.dorsal }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.mins }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.fgm }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.fga }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.fgperc|floatformat:0 }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.threepm }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.threepa }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.threepperc|floatformat:0 }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.ftm }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.fta }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.ftperc|floatformat:0 }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.reb }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.ast }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.stl }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.blk }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.turnover }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.pf }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.pts }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<h2 class="font-bold text-2xl text-gray-600">{{  partido.equipo_visitante  }}<small class="ms-2 font-semibold text-gray-500">
    {% if player.id_team.id_team == partido.id_equipo_visitante %}
        <a class="partido" href="{% url 'statistics:shot_plot' partido.id_game %}">Añadir estadísticas</a>
    {% endif %}
</small>
</h2>

<div class="relative overflow-x-auto shadow-md sm:rounded-lg mt-8">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50">
            <tr>
                <th scope="col" class="px-6 py-3 text-left">Jugador</th>
                <th scope="col" class="px-4 py-3 text-center">MIN</th>
                <th scope="col" class="px-4 py-3 text-center">FGM</th>
                <th scope="col" class="px-4 py-3 text-center">FGA</th>
                <th scope="col" class="px-4 py-3 text-center">FG%</th>
                <th scope="col" class="px-4 py-3 text-center">3PM</th>
                <th scope="col" class="px-4 py-3 text-center">3PA</th>
                <th scope="col" class="px-4 py-3 text-center">3P%</th>
                <th scope="col" class="px-4 py-3 text-center">FTM</th>
                <th scope="col" class="px-4 py-3 text-center">FTA</th>
                <th scope="col" class="px-4 py-3 text-center">FT%</th>
                <th scope="col" class="px-4 py-3 text-center">REB</th>
                <th scope="col" class="px-4 py-3 text-center">AST</th>
                <th scope="col" class="px-4 py-3 text-center">STL</th>
                <th scope="col" class="px-4 py-3 text-center">BLK</th>
                <th scope="col" class="px-4 py-3 text-center">TO</th>
                <th scope="col" class="px-4 py-3 text-center">PF</th>
                <th scope="col" class="px-4 py-3 text-center">PTS</th>
            </tr>
        </thead>
        <tbody>
            {% for estadistica in estadisticas_visitante %}
            <tr class="bg-white border-b hover:bg-gray-50">
                <th scope="row" class="px-6 py-2 font-medium text-gray-900 whitespace-nowrap text-left">{{ estadistica.id_player.first_name }}, #{{ estadistica.id_player.dorsal }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.mins }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.fgm }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.fga }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.fgperc|floatformat:0 }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.threepm }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.threepa }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.threepperc|floatformat:0 }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.ftm }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.fta }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.ftperc|floatformat:0 }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.reb }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.ast }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.stl }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.blk }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.turnover }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.pf }}</td>
                <td class="px-4 py-2 text-center">{{ estadistica.pts }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}