basketball/basketball/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.index, name='index'),
    path("accounts/", include('allauth.urls')),
    path("calendar/",include("calendar_basket.urls")),
    path("clasificacion/",include("clasificacion.urls")),
    path("statistics/",include("statistics_basketball.urls")),
    path("perfil/",include("perfil.urls")),
    path('api/v1/api-auth/', include('rest_framework.urls', namespace='rest_framework'), name='api-auth'),
    path('api/v1/', include('calendar_basket.api.v1.urls')),
    path('api/v1/', include('clasificacion.api.v1.urls')),
    path('api/v1/', include('statistics_basketball.api.v1.urls')),
    path('api/v1/', include('perfil.api.v1.urls')),
]

basketball/calendar_basket/api/v1/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'calendar', views.CalendarViewSet)
router.register(r'teams', views.TeamViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

basketball/calendar_basket/urls.py
from django.urls import path
from . import views

app_name = "calendar"

urlpatterns = [
    path("", views.calendar, name='calendar_basket'),
]

basketball/clasificacion/api/v1/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'clasificacion', views.ClasificacionViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

basketball/clasificacion/urls.py
from django.urls import path
from . import views

app_name = "clasificacion"

urlpatterns = [
    path("", views.clasificacion, name="clasificacion"),
]

basketball/perfil/api/v1/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'players', views.PlayersViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

basketball/perfil/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = "perfil"

urlpatterns = [
    path('complete-player-profile/', views.complete_player_profile_view, name='complete_player_profile'),
    path('', views.perfil, name='perfil'),
]

basketball/statistics_basketball/api/v1/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'statistics', views.StatisticsViewSet)
router.register(r'team-statistics', views.TeamStatisticsViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

basketball/statistics_basketball/urls.py
from django.urls import path
from . import views

app_name = "statistics"

urlpatterns = [
    path("", views.statistics, name="statistics"),
    path("<int:id_game>/", views.view_statistics, name="statistics_game"),
    path("add/<int:id_game>/", views.add_statistics, name="add_statistics"),
    path("shot_plot/<int:id_game>/", views.bokeh_shot_stats, name="shot_plot"),
    path("playerstats/", views.bokeh_player_stats, name="player_stats"),
    path("team_statistics/", views.team_statistics, name="team_statistics"),
]

basketball/templates/socialaccount/providers/box/urls.py
from allauth.socialaccount.providers.oauth.urls import default_urlpatterns

from .provider import BoxOAuth2Provider


urlpatterns = default_urlpatterns(BoxOAuth2Provider)

basketball/templates/socialaccount/providers/daum/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import DaumProvider


urlpatterns = default_urlpatterns(DaumProvider)

basketball/templates/socialaccount/providers/drip/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import DripProvider


urlpatterns = default_urlpatterns(DripProvider)

basketball/templates/socialaccount/providers/edx/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import EdxProvider


urlpatterns = default_urlpatterns(EdxProvider)

basketball/templates/socialaccount/providers/fxa/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import FirefoxAccountsProvider


urlpatterns = default_urlpatterns(FirefoxAccountsProvider)

basketball/templates/socialaccount/providers/line/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import LineProvider


urlpatterns = default_urlpatterns(LineProvider)

basketball/templates/socialaccount/providers/miro/urls.py
from allauth.socialaccount.providers.miro.provider import MiroProvider
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns


urlpatterns = default_urlpatterns(MiroProvider)

basketball/templates/socialaccount/providers/okta/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import OktaProvider


urlpatterns = default_urlpatterns(OktaProvider)

basketball/templates/socialaccount/providers/saml/urls.py
from django.urls import include, path, re_path

from . import views


urlpatterns = [
    re_path(
        r"^saml/(?P<organization_slug>[^/]+)/",
        include(
            [
                path(
                    "acs/",
                    views.acs,
                    name="saml_acs",
                ),
                path(
                    "acs/finish/",
                    views.finish_acs,
                    name="saml_finish_acs",
                ),
                path(
                    "sls/",
                    views.sls,
                    name="saml_sls",
                ),
                path(
                    "metadata/",
                    views.metadata,
                    name="saml_metadata",
                ),
                path(
                    "login/",
                    views.login,
                    name="saml_login",
                ),
            ]
        ),
    )
]

basketball/templates/socialaccount/providers/vk/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import VKProvider


urlpatterns = default_urlpatterns(VKProvider)

basketball/templates/socialaccount/providers/xing/urls.py
from allauth.socialaccount.providers.oauth.urls import default_urlpatterns

from .provider import XingProvider


urlpatterns = default_urlpatterns(XingProvider)

basketball/templates/socialaccount/providers/ynab/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import YNABProvider


urlpatterns = default_urlpatterns(YNABProvider)

basketball/templates/socialaccount/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path(
        "login/cancelled/",
        views.login_cancelled,
        name="socialaccount_login_cancelled",
    ),
    path("login/error/", views.login_error, name="socialaccount_login_error"),
    path("signup/", views.signup, name="socialaccount_signup"),
    path("connections/", views.connections, name="socialaccount_connections"),
]

basketball/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}BasketAPP{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.min.css" rel="stylesheet">
  {% block extra_head %}{% endblock %}
</head>
<body>
  <header>
    <nav class="bg-white border-gray-20">
      <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4 ">
        <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-ball-basketball" width="44" height="44" viewBox="0 0 24 24" stroke-width="1.5" stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
            <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0" />
            <path d="M5.65 5.65l12.7 12.7" />
            <path d="M5.65 18.35l12.7 -12.7" />
            <path d="M12 3a9 9 0 0 0 9 9" />
            <path d="M3 12a9 9 0 0 1 9 9" />
          </svg>
          <span class="self-center text-2xl font-semibold whitespace-nowrap text-gray-800">BasketAPP</span>
        </a>
        <button data-collapse-toggle="navbar-dropdown" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-dropdown" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
          </svg>
        </button>
        <div class="hidden w-full md:block md:w-auto" id="navbar-dropdown">
          <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
            <li>
              <button id="dropdownNavbarLink" data-dropdown-toggle="dropdownNavbar" class="flex items-center justify-between w-full py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-green-500 md:p-0 md:w-auto">Liga <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
              </svg></button>
              <div id="dropdownNavbar" class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44">
                <ul class="py-2 text-sm text-gray-700 dark:text-gray-400" aria-labelledby="dropdownLargeButton">
                  <li>
                    <a href="/calendar" class="block px-4 py-2 hover:bg-gray-100">Calendario</a>
                  </li>
                  <li>
                    <a href="/clasificacion" class="block px-4 py-2 hover:bg-gray-100">Clasificación</a>
                  </li>
                </ul>
              </div>
            </li>
            <li>
              <a href="{% url 'statistics:team_statistics' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-green-500 md:p-0 dark:text-white">Estadísticas equipos</a>
            </li>
            <li>
              <a href="{% url 'statistics:statistics' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-green-500 md:p-0 dark:text-white">Añadir estadísticas</a>
            </li>
            <li>
              <a href="{% url 'statistics:player_stats' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-green-500 md:p-0 dark:text-white">Estadísticas ind.</a>
            </li>
            <li>
              <button id="dropdownNavbarLinkProfile" data-dropdown-toggle="dropdownNavbarProfile" class="flex items-center justify-between w-full py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-green-500 md:p-0 md:w-auto">Usuario <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
              </svg></button>
              <div id="dropdownNavbarProfile" class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44">
                <ul class="py-2 text-sm text-gray-700 dark:text-gray-400" aria-labelledby="dropdownLargeButton">
                  {% if user.is_authenticated %}
                    <li>
                      <a href="{% url 'perfil:perfil' %}" class="block px-4 py-2 hover:bg-gray-100">Perfil</a>
                    </li>
                    <li>
                      <a href="{% url 'account_logout' %}" class="block px-4 py-2 hover:bg-gray-100">Cerrar sesión</a>
                    </li>
                  {% else %}
                    <li>
                      <a href="{% url 'account_login' %}" class="block px-4 py-2 hover:bg-gray-100">Iniciar sesión</a>
                    </li>
                    <li>
                      <a href="{% url 'account_signup' %}" class="block px-4 py-2 hover:bg-gray-100">Registrarse</a>
                    </li>
                  {% endif %}
                </ul>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>    
  </header>
  <div class="container mx-auto max-w-screen-xl">
      <h1>{% block page_title %}{% endblock %}</h1>
      {% block content %}{% endblock %}
  </div>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.min.js"></script>

</html>

basketball/templates/django_filters/widgets/multiwidget.html
{% for widget in widget.subwidgets %}{% include widget.template_name %}{% if forloop.first %}-{% endif %}{% endfor %}

basketball/templates/home/index.html
{% extends "base.html" %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="text-center mb-20">
        <h1 class="sm:text-3xl text-2xl font-medium title-font text-gray-900 mb-4">BasketAPP</h1>
        <p class="text-base leading-relaxed xl:w-2/4 lg:w-2/4 mx-auto text-gray-500s">
          Aplicación creada para ver resultados y añadir estadísticas de la liga:<br>
          FBCV - Senior Masculino - 1ª Zonal - Grupo B.
        </p>
        <div class="flex mt-6 justify-center">
          <div class="w-16 h-1 rounded-full bg-green-500 inline-flex"></div>
        </div>
      </div>
      <div class="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4 md:space-y-0 space-y-6">
        <div class="p-4 md:w-1/4 flex flex-col text-center items-center">
          <div class="w-20 h-20 inline-flex items-center justify-center rounded-full bg-green-100 text-green-500 mb-5 flex-shrink-0">
            <svg class="w-10 h-10" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
              <path d="M0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm14-7.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1Zm0 4a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1Zm-5-4a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1Zm0 4a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1Zm-5-4a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1Zm0 4a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1ZM20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4Z"/>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">Calendario y Clasificación</h2>
            <p class="leading-relaxed text-base">Calendario y clasificación de la liga.</p>
            <a class="mt-3 text-green-500 inline-flex items-center" href="{% url 'calendar:calendar_basket' %}">Calendario 
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
            <a class="mt-3 text-green-500 inline-flex items-center" href="{% url 'clasificacion:clasificacion' %}">Clasificación 
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
        <div class="p-4 md:w-1/4 flex flex-col text-center items-center">
          <div class="w-20 h-20 inline-flex items-center justify-center rounded-full bg-green-100 text-green-500 mb-5 flex-shrink-0">
            <svg class="w-10 h-10" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 18">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 3a3 3 0 1 1-1.614 5.53M15 12a4 4 0 0 1 4 4v1h-3.348M10 4.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0ZM5 11h3a4 4 0 0 1 4 4v2H1v-2a4 4 0 0 1 4-4Z"/>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">Estadísticas de equipos</h2>
            <p class="leading-relaxed text-base">Estadísticas generales de los equipos.</p>
            <a class="mt-3 text-green-500 inline-flex items-center" href="{% url 'statistics:team_statistics' %}">Est. equipos 
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
        <div class="p-4 md:w-1/4 flex flex-col text-center items-center">
          <div class="w-20 h-20 inline-flex items-center justify-center rounded-full bg-green-100 text-green-500 mb-5 flex-shrink-0">
            <svg class="w-10 h-10" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 18">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 8a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm-2 3h4a4 4 0 0 1 4 4v2H1v-2a4 4 0 0 1 4-4Z"/>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">Añadir estadísticas</h2>
            <p class="leading-relaxed text-base">Introducir estadísticas individuales.</p>
            <a class="mt-3 text-green-500 inline-flex items-center" href="{% url 'statistics:statistics' %}">Añadir estadísticas 
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
        <div class="p-4 md:w-1/4 flex flex-col text-center items-center">
          <div class="w-20 h-20 inline-flex items-center justify-center rounded-full bg-green-100 text-green-500 mb-5 flex-shrink-0">
            <svg class="w-10 h-10" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"fill="none" viewBox="0 0 17 18">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 12v5m5-9v9m5-5v5m5-9v9M1 7l5-6 5 6 5-6"/>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">Resumen estadísticas</h2>
            <p class="leading-relaxed text-base">Resumen estadísticas individuales.</p>
            <a class="mt-3 text-green-500 inline-flex items-center" href="{% url 'statistics:player_stats' %}">Est. individuales 
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% endblock %}